# Generated by Django 5.0.6 on 2024-06-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sdName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50)),
                ('rut', models.IntegerField(default=11111111)),
                ('DVrut', models.CharField(default=1, max_length=1)),
                ('imgUser', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('sub_title', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompra', models.CharField(max_length=100)),
                ('precioCompra', models.IntegerField(default=0)),
                ('fecha', models.DateField(verbose_name='dd-mm-yyyy')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='tienda.post')),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='tienda.usuario')),
            ],
        ),
    ]
