# Generated by Django 5.0.6 on 2024-06-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario_compra_post_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='post',
            new_name='postID',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='usuario',
            new_name='usuarioID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
    ]
