# Generated by Django 5.0.6 on 2024-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_post_compra_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(default=11111111, unique=True),
        ),
    ]
