# Generated by Django 5.0.6 on 2024-06-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_post_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCompra', models.IntegerField(default=0)),
                ('compraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compra')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.post')),
                ('usuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
