# Generated by Django 5.0.6 on 2024-06-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_transaccioncompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncompra',
            name='postID',
        ),
        migrations.AddField(
            model_name='transaccioncompra',
            name='cantidadCompra',
            field=models.IntegerField(default=0),
        ),
    ]
