# Generated by Django 5.0.6 on 2024-06-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_transaccioncompra_postid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncompra',
            name='compraID',
        ),
    ]
