# Generated by Django 5.0.6 on 2024-06-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0013_remove_transaccioncompra_compraid"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='transaccioncompra',
        #     name='fechaTran',
        #     field=models.DateField(auto_created=True, default=0),
        # ),
    ]
