# Generated by Django 5.0.6 on 2024-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0014_transaccioncompra_fechatran"),
    ]

    operations = [
        #     migrations.AlterField(
        #         model_name='transaccioncompra',
        #         name='fechaTran',
        #         field=models.DateField(auto_created=True, default='00-00-0000'),
        #     ),
    ]
