# Generated by Django 5.0.6 on 2024-06-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0016_alter_transaccioncompra_fechatran"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='transaccioncompra',
        #     name='fechaTran',
        #     field=models.DateField(auto_created=True),
        # ),
    ]
