# Generated by Django 5.0.6 on 2024-06-30 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0018_alter_transaccioncompra_fechatran"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='transaccioncompra',
        #     name='fechaTran',
        #     field=models.DateField(default=django.utils.timezone.now),
        # ),
    ]
