# Generated by Django 5.0.6 on 2024-06-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0019_alter_transaccioncompra_fechatran"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='transaccioncompra',
        #     name='fechaTran',
        # ),
    ]
