# Generated by Django 5.0.6 on 2024-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_remove_transaccioncompra_fechatran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
