# Generated by Django 5.0.6 on 2024-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_transaccioncompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncompra',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccioncompra',
            name='cantidadCompra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccioncompra',
            name='totalCompra',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
