# Generated by Django 5.0.6 on 2024-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_remove_transaccioncompra_fecha_alter_post_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncompra',
            name='fechaTran',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
